name: Create Archive
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Archive Release
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./wordpress-menu-rest.zip ./
      - uses: actions/upload-artifact@master
        with:
          name: wordpress-menu-rest
          path: wordpress-menu-rest-zip
